<?php
$json = file_get_contents(__DIR__.'/../../config/config_linebot.json');
$config = json_decode($json,true);

$checkBeenBind = $conmysql->prepare("SELECT member_no FROM gcmemberaccount WHERE line_token = :line_id");
$checkBeenBind->execute([':line_id' => $user_id]);

$baseUrl = 'https://cdn.thaicoop.co/linebot/imagemap/nkh_new2.jpg';
if($checkBeenBind->rowCount() > 0){
	$datas = [];
	$datas["type"] = "imagemap";
	$datas["baseUrl"] = $baseUrl.'?_ignorid';
	$datas["altText"] = "เมนูทั้งหมด";
	$datas["baseSize"]["width"] = 1040;
	$datas["baseSize"]["height"] = 701;
	$datas["actions"][0]["type"] = "message";
	$datas["actions"][0]["area"]["x"] = 35;
	$datas["actions"][0]["area"]["y"] = 14;
	$datas["actions"][0]["area"]["width"] = 264;
	$datas["actions"][0]["area"]["height"] = 229;
	$datas["actions"][0]["text"] = "ข้อมูลสมาชิก";
	$datas["actions"][1]["type"] = "message";
	$datas["actions"][1]["area"]["x"] = 372;
	$datas["actions"][1]["area"]["y"] = 18;
	$datas["actions"][1]["area"]["width"] = 313;
	$datas["actions"][1]["area"]["height"] = 221;
	$datas["actions"][1]["text"] = "กองทุนสวัสดิการ";
	$datas["actions"][2]["type"] = "message";
	$datas["actions"][2]["area"]["x"] = 771;
	$datas["actions"][2]["area"]["y"] = 16;
	$datas["actions"][2]["area"]["width"] = 257;
	$datas["actions"][2]["area"]["height"] = 223;
	$datas["actions"][2]["text"] = "เงินกู้";
	$datas["actions"][3]["type"] = "message";
	$datas["actions"][3]["area"]["x"] = 39;
	$datas["actions"][3]["area"]["y"] = 264;
	$datas["actions"][3]["area"]["width"] = 263;
	$datas["actions"][3]["area"]["height"] = 193;
	$datas["actions"][3]["text"] = "หุ้น";
	$datas["actions"][4]["type"] = "message";
	$datas["actions"][4]["area"]["x"] = 378;
	$datas["actions"][4]["area"]["y"] = 264;
	$datas["actions"][4]["area"]["width"] = 308;
	$datas["actions"][4]["area"]["height"] = 196;
	$datas["actions"][4]["text"] = "ค้ำประกัน";
	$datas["actions"][5]["type"] = "message";
	$datas["actions"][5]["area"]["x"] = 766;
	$datas["actions"][5]["area"]["y"] = 264;
	$datas["actions"][5]["area"]["width"] = 262;
	$datas["actions"][5]["area"]["height"] = 203;
	$datas["actions"][5]["text"] = "ใบเสร็จ";
	$datas["actions"][6]["type"] = "message";
	$datas["actions"][6]["area"]["x"] = 37;
	$datas["actions"][6]["area"]["y"] = 481;
	$datas["actions"][6]["area"]["width"] = 269;
	$datas["actions"][6]["area"]["height"] = 197;
	$datas["actions"][6]["text"] = "ปันผล-เฉลี่ยคืน";
	$datas["actions"][7]["type"] = "message";
	$datas["actions"][7]["area"]["x"] = 376;
	$datas["actions"][7]["area"]["y"] = 476;
	$datas["actions"][7]["area"]["width"] = 309;
	$datas["actions"][7]["area"]["height"] = 204;
	$datas["actions"][7]["text"] = "ฌาปนกิจ";
	$datas["actions"][8]["type"] = "message";
	$datas["actions"][8]["area"]["x"] = 755;
	$datas["actions"][8]["area"]["y"] = 481;
	$datas["actions"][8]["area"]["width"] = 267;
	$datas["actions"][8]["area"]["height"] = 215;
	$datas["actions"][8]["text"] = "เรียกเก็บประจำเดือน";
	$arrPostData["messages"][0] = $datas;
	$arrPostData["replyToken"] = $reply_token;
}else{
	$altText = "ท่านยังไม่ได้ผูกบัญชี";
	$dataMs = $lineLib->notBindAccount();
	$dataPrepare = $lineLib->prepareFlexMessage($altText,$dataMs);
	$arrPostData["messages"] = $dataPrepare;
	$arrPostData["replyToken"] = $reply_token;
}
?>